steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/next_supabase_boilerplate_raw:latest",
        "--build-arg",
        "NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}",
        "--build-arg",
        "NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}",
        ".",
      ]
  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/next_supabase_boilerplate_raw:latest",
      ]
images:
  - "us-east1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/next_supabase_boilerplate_raw:latest"
